CREATE TABLE IF NOT EXISTS players (
    uuid        CHAR(36)     NOT NULL PRIMARY KEY,
    mcid        VARCHAR(16)  NOT NULL,
    discord_id  VARCHAR(32)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_discord (discord_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
